### ISSUE TITLE
Linkify URL on report detail pages

### ISSUE THREAD

**Issue by cptvitamin** [edx/pa11ycrawler#29]
On the report detail pages the URL for the page the report references is not a link.  Would be great if it was and target=_blank.

**Comment by singingwolfboy** [comment]
@cptvitamin, how important is it that this link be `target="_blank"`? Seems like leaving it as a regular link is more standard, and you can always middle-click to open the page in a new tab.

**Comment by cptvitamin** [comment]
@singingwolfboy not important.
